/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "LED.hpp"

extern "C" void EXTI15_10_IRQHandler() {
	DRIVER_GPIO::GPIOC13_Conf.ptrGpioISR();
}

extern "C" void EXTI9_5_IRQHandler() {
	DRIVER_GPIO::GPIOB7_Conf.ptrGpioISR();
}

int main(void)
{
	DRIVER_GPIO::GPIOC13_Conf.ptrGpioISR = DRIVER_GPIO::PUSH_BOTTOM::PUSH_ISR;
	DRIVER_GPIO::GPIOB7_Conf.ptrGpioISR = DRIVER_GPIO::LED::LED_ISR;

	DRIVER_GPIO::LED::LED_ClockPeriph();
	DRIVER_GPIO::PUSH_BOTTOM::PUSH_ClockPeriph();

	DRIVER_GPIO::LED::LED_Config();
	DRIVER_GPIO::LED::LED_InterruptConfig();

	DRIVER_GPIO::PUSH_BOTTOM::PUSH_Config();
	DRIVER_GPIO::PUSH_BOTTOM::PUSH_InterruptConfig();
	/* Loop forever */
	while(1);
}
